config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :shorts, only: [:index, :show, :destroy]
    resources :user, only: [:index, :destroy, :show, :edit, :update]
    resources :admin_advertisements, only: [:index, :show, :destroy]
  end

  devise_for :users
  
  authenticated :user do
    root 'static_pages#welcome'
  end
  
  root 'static_pages#home'
  resources :shorts, only: [:show, :create, :new]
  resources :advertisements
  get 'greetings/hello'
  get ":id", to: "static_pages#redirect"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @short = Short.new
    @short2 = Short.last
  end
  
  def redirect
    if Advertisement.count > 0
      @advertisement = Advertisement.order("RANDOM()").first
      @advertiser = User.find(@advertisement.user_id).company
    end
    @redirection = Short.find(params[:id].to_i(36)).url
  end
  
  def welcome
    if current_user.is_female == true
      @gender = "Ms."
    else
      @gender = "Mr."
    end
    @name = current_user.name
    
    if current_user.admin?
      @role = "administrator"
    else
      @role = "advertiser"
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "| Home") %>

<div class="container">
  
  <div class="row">
    <div class="col-md-12">
      <div class="page-header center">
        <h1>Shorten your links easily <small> Short and see an URL here</small></h1>
      </div>
    </div>
  </div>

 <%= render 'shared/show_flash' %>

  <div class="row">  
    <div class="col-md-8 col-md-offset-2 center">
      <%= render 'shorts/form' %>
    </div>
  </div>    
  
  <% if flash.notice == 'Short was successfully created.' %>
    <div class="row" id="margen">
      <div class="col-md-8 col-md-offset-2 center">
        <%= render 'shorts/home_form' %>
      </div>
    </div>
  <% end %>

</div>

app/views/static_pages/redirect.html.erb
<% provide(:title, "| Redirecting") %>
<body onload=timedCount()>
<div class="container">
  
  <div class="row">
    <div class="col-md-12">
      <div class="page-header center">
        <h1>Redirecting <small> You will skip the advertisement in: <span id="seconds">my_input</span> seconds.</small></h1>
      </div>
    </div>
  </div>

  <div class="row"> 
    <div class="col-md-12 center wrap-word">
      <% unless @advertisement.nil? %>
        <h2 id="title"><%= @advertisement.title %></h2>
        <%= image_tag(@advertisement.picture, class: 'img-responsive center-block', alt: "anuncio", id:'borde') %>
      <%end%>
      <% if !@advertiser.blank? %>
        <h4><strong>Advertisement sponsored by:</strong> <%= @advertiser %></h4>
      <%end%>
    </div>
  </div>
  
  <div class="row"> 
    <div class="col-md-12 center">
      <% if !@redirection.blank? %>
      <%= link_to "Skip advertisement now", @redirection, id: "signup", class: "btn btn-lg btn-warning", :target => "_blank" %>
      <% end %>
    </div>
  </div>
  
  <script>
    var c=5;
    $(signup).hide();
    function timedCount(){
    	$("#seconds").html(c);
    	c=c-1;
    	if(c==-1){
    	  $(signup).show();
    	  return;
    	}
    	setTimeout("timedCount()",1000);
    }
  </script>
  
</div>

app/views/static_pages/welcome.erb
<% provide(:title, "| Welcome") %>

<div class="container">
  
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="page-header center">
        <h1>Welcome <small> to your account</small></h1>
      </div>
      
      <%= render 'shared/show_flash' %>
      
      <div class="panel">
        <div class="panel-heading text-center">
          <h3><strong>Hello <% unless @name.blank? %><%= @gender %> <%= @name %><% end %></strong></h3>
        </div>
        <h4 class='text-center'>This is the administration page of your profile.
        <br>As <strong><%= @role %></strong> you can do the followings things:</br></h4>
      </div>
      
      <div class="btn-group btn-group-justified" role="group" aria-label="...">
          <%if current_user.admin %>
            <div class="btn-group" role="group"><%= link_to "Manage URLs", admin_shorts_path, class: 'btn btn-lg btn-info' %></div>
            <div class="btn-group" role="group"><%= link_to "Manage Users", admin_user_index_path, class: 'btn btn-lg btn-info' %></div>
            <div class="btn-group" role="group"><%= link_to "Manage Ads",  admin_admin_advertisements_path, class: 'btn btn-lg btn-info' %></div>
          <%else%>
            <div class="btn-group" role="group"><%= link_to "Manage Ads", advertisements_path, class: 'btn btn-lg btn-info' %></div>
          <%end%>
        </ul>
      </div>
      
    </div>
  </div>

</div>