config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :shorts, only: [:index, :show, :destroy]
    resources :user, only: [:index, :destroy, :show, :edit, :update]
    resources :admin_advertisements, only: [:index, :show, :destroy]
  end

  devise_for :users
  
  authenticated :user do
    root 'static_pages#welcome'
  end
  
  root 'static_pages#home'
  resources :shorts, only: [:show, :create, :new]
  resources :advertisements
  get 'greetings/hello'
  get ":id", to: "static_pages#redirect"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/short.rb
class Short < ApplicationRecord
    VALID_URL_REGEX = /\A((http|https|ftp|ftps):\/\/)?(([a-z0-9]+\:)?[a-z0-9]+\@)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z/
    before_validation :add_url_protocol
    validates :url, presence: true, format: { with: VALID_URL_REGEX }
    
    def short_url
        self.id.to_s(36)
    end
    
    def self.search(term)
        if term
          where('url LIKE ?', "%#{term}%").order('id ASC')
        else
          order('id ASC') 
        end
    end
    
    private
    
        def add_url_protocol
            unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
                self.url = "http://#{self.url}"
            end
        end
end

app/controllers/admin/shorts_controller.rb
class Admin::ShortsController < Admin::ApplicationController
    
  # GET /shorts
  # GET /shorts.json
  def index
    @shorts = Short.search(params[:term]).paginate(page: params[:page]).order("url ASC")
  end
  
  def show
  end
  
  # DELETE /shorts/1
  # DELETE /shorts/1.json
  def destroy
    @short = Short.find(params[:id])
    @short.destroy
    respond_to do |format|
      format.html { redirect_to admin_shorts_path, notice: 'Short was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def short_params
      params.require(:short).permit(:url, :term)
    end
    
end

app/controllers/shorts_controller.rb
class ShortsController < ApplicationController
  before_action :set_short, only: [:show]

  # GET /shorts/1
  # GET /shorts/1.json
  def show
  end

  # GET /shorts/new
  def new
    @short = Short.new
  end


  # POST /shorts
  # POST /shorts.json
  def create
    @short = Short.new(short_params)
    respond_to do |format|
      if @short.save
        format.html { redirect_to root_path, notice: 'Short was successfully created.' }
        format.json { render :new, status: :created, location: @short }
      else
        format.html { render :new }
        format.json { render json: @short.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_short
      @short = Short.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_params
      params.require(:short).permit(:url)
    end
end

app/helpers/admin/shorts_helper.rb
module Admin::ShortsHelper
end

app/helpers/shorts_helper.rb
module ShortsHelper
    
    def link_url(url)
        link_to url, url, :target => "_blank" 
    end
    
    def short(id)
        Short.find(id)
    end
    
end

app/views/shorts/_edit_form.html.erb
<%= form_for(short) do |f| %> 
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :url, "Your URL to edit:" %>
  <div class="input-group">
    <%= f.text_field :url, class: "form-control"%>
    <span class="input-group-btn"><%= f.submit "Update short", class: "btn btn-default" %></span>
  </div>
<% end %>

app/views/shorts/_form.html.erb
<%= form_for(@short) do |f| %> 
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :url, "Introduce an URL:" %>
  <div class="input-group">
    <%= f.text_field :url, class: "form-control", placeholder:"http://your-url.com" %>
    <span class="input-group-btn"><%= f.submit "Create short", class: "btn btn-success" %></span>
  </div>
<% end %>

app/views/shorts/_home_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h4>See your URL information</h4></div>
    <div class="panel-body wrap-word">
        <h5><strong>Url: </strong><%= link_url(@short2.url) %></h5>
        <h5><strong>Shorted Url: </strong><%= link_to request.base_url+'/'+@short2.short_url, request.base_url+'/'+@short2.short_url, id: 'id-of-link', :target => "_blank" %></h5>
    </div>
    <div class="panel-footer">
        <h6>URL shortened by URL SHORTENER APPLICATION.</h6>
    </div>
</div>

app/views/shorts/edit.html.erb
<% if current_user.try(:admin?) %>
    <% provide(:title, "| Update Short Info") %>
        <div class="page-header">
          <h1>Edit <small>Your URL</small></h1>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><h4>Edit your URL path</h4></div>
            <div class="panel-body">
                <%= render 'edit_form', short: @short %>
            </div>
            <div class="panel-footer">
                <%= link_to 'Show', @short,  class: "btn btn-info" %> 
                <%= link_to 'Back', :back, class: "btn btn-default" %>
            </div>
        </div>
<% else %>
  <% controller.redirect_to root_path, notice: 'Need to be administrator for this.' %> 
<% end %>

app/views/shorts/index.html.erb
<% if current_user.try(:admin?) %>
  <% provide(:title, "| See the Shorts") %>
  
  <div class="page-header">
    <h1>Shorts <small>See the shortened URL here</small></h1>
  </div>
  
  <%= render 'shared/show_flash' %>
  
  <div class="panel panel-default">
    <div class="panel-heading"><h4>Manage shortened URLs</h4></div>
    <div class="panel-body">
    
      <table class="table table-striped">
        <tbody>
          <% @shorts.each do |short| %>
            <tr>
              <td class='col-md-9'><h5><strong>URL: </strong><%= link_url(short.url) %></h5></td>
              <td><%= link_to 'Show', short, class: "btn btn-info" %></td>
              <td><%= link_to 'Edit', edit_short_path(short), class: "btn btn-primary" %></td>
              <td><%= link_to 'Destroy', short, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <div class="text-center">
        <%= will_paginate %>
      </div>
    
    </div>
    <div class="panel-footer">
        <%= link_to 'New Short', new_short_path, class: "btn btn-success" %>
        <%= link_to 'Back', :back, class: "btn btn-default" %>
    </div>
  </div>
  
<% else %>
  <% controller.redirect_to root_path, notice: 'Need to be administrator for this.' %> 
<% end %>
  

app/views/shorts/new.html.erb
<% provide(:title, "| Create a Short") %>
<div class="page-header center">
  <h1>New Short <small>Short your URL here</small></h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <%= render 'form', short: @short %>
  </div>
</div>

<div class="boton_inicio center">
    <%= link_to 'Back', :back, class: "btn btn-default" %>
</div>

app/views/shorts/show.html.erb
<% provide(:title, "| Shorts Info") %>

<% if !flash.empty? %>
    <div class="alert alert-success" role="alert">
        <p id="notice"><%= flash[:notice] %></p>
    </div>
<% end %>

<div class="page-header">
  <h1>Show <small>Your URL</small></h1>
</div>

<div class="panel panel-default">
    <div class="panel-heading"><h4>See your URL information</h4></div>
    <div class="panel-body">
        <h5><strong>Url: </strong><%= link_url(@short.url) %></h5>
        <h5><strong>Shorted Url: </strong><%= link_to request.base_url+'/'+@short.short_url, static_pages_redirect_path(rid: @short.id), id: 'id-of-link', :target => "_blank" %></h5>
    </div>
    <div class="panel-footer">
    <%= link_to 'Edit', edit_admin_short_path(@short), class: "btn btn-primary" %> 
    <%= link_to 'Back', :back, class: "btn btn-default" %>
    </div>
</div>