config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :shorts, only: [:index, :show, :destroy]
    resources :user, only: [:index, :destroy, :show, :edit, :update]
    resources :admin_advertisements, only: [:index, :show, :destroy]
  end

  devise_for :users
  
  authenticated :user do
    root 'static_pages#welcome'
  end
  
  root 'static_pages#home'
  resources :shorts, only: [:show, :create, :new]
  resources :advertisements
  get 'greetings/hello'
  get ":id", to: "static_pages#redirect"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 80 }
  validates :picture, presence: true
  validate  :picture_size, on: :create
  mount_uploader :picture, PictureUploader
  
  def self.search(term)
    if term
      where('title LIKE ?', "%#{term}%").order('id DESC')
    else
      order('id DESC') 
    end
  end
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB.")
    end
  end

end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
    before_action :correct_user, only: [:show, :destroy, :edit, :update]

    
    def index
        @advertisements = current_user.advertisements.search(params[:term]).paginate(page: params[:page])
    end
    
    def show
    end
    
    def new
        @advertisement = Advertisement.new
    end
    
    def edit
        @advertisement = Advertisement.find(params[:id])
    end
    
    def create
        @advertisement = current_user.advertisements.build(advertisement_params)
        respond_to do |format|
          if @advertisement.save
            format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully created.' }
            format.json { render :new, status: :created, location: @advertisement }
          else
            format.html { render :new }
            format.json { render json: @advertisement.errors, status: :unprocessable_entity }
          end
        end
    end

    def update
        @advertisement = Advertisement.find(params[:id])
        respond_to do |format|
          if @advertisement.update(advertisement_params)
            format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully updated.' }
            format.json { render :show, status: :ok, location: @short }
          else
            format.html { render :edit }
            format.json { render json: @advertisement.errors, status: :unprocessable_entity }
          end
        end
    end
    
    def destroy
        @advertisement = Advertisement.find(params[:id])
        @advertisement.destroy
        respond_to do |format|
            format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    
    private
        
        def advertisement_params
           params.require(:advertisement).permit(:title, :picture, :term)
        end
    
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
    
    def advert(id)
        Advertisement.find(id)
    end
    
end

app/views/advertisements/_edit_form.html.erb
<div class="row">
  <div class="col-md-12 ">
  <%= form_for(@advertisement) do |f| %> 
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :title, "Select a new title for your advertisement: " %>
    <%= f.text_field :title, class: "form-control", placeholder:"Title for your advertisement" %>
    <%= f.label :title, "Select a new picture for your advertisement: " %>
    <img id="prev" class="img-responsive" >
        <span class="btn btn-default btn-file btn-block">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', id: "picture" %> Search… 
        </span>
    <%= f.submit "Update advertisement", class: "btn btn-primary", id: 'signup'%>
  <% end %>
  </div>
</div>

<script>
  $('form').submit(function() {
  var accept, size_in_megabytes, extension;
  accept = true;
  size_in_megabytes = $('#picture')[0].files[0].size / 1024 / 1024;
  extension = /\.(gif|jpg|jpeg|png)$/i.test(document.getElementById('picture').value);
  if (size_in_megabytes > 5) {
    accept = false;
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
  if (!extension){
    accept = false;
    alert('This document extension is not allowed.');
  }
  return accept;
});
</script>

<script>
function readURL(input) {

  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#prev').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}

$("#picture").change(function(){
    readURL(this);
});
</script>

app/views/advertisements/_form.html.erb
<div class="row">
  <div class="col-md-12 ">
  <%= form_for(@advertisement) do |f| %> 
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :title, "Introduce a title for your advertisement: " %>
    <%= f.text_field :title, class: "form-control", placeholder:"Title for your advertisement" %>
    <%= f.label :title, "Select a picture for your advertisement: " %>
    <img id="prev" class="img-responsive" >
        <span class="btn btn-default btn-file btn-block">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', id: "picture" %> Search… 
        </span>
    <%= f.submit "Create advertisement", class: "btn btn-success", id: 'signup'%>
  <% end %>
  </div>
</div>

<script>
  $('form').submit(function() {
  var accept, size_in_megabytes, extension;
  accept = true;
  size_in_megabytes = $('#picture')[0].files[0].size / 1024 / 1024;
  extension = /\.(gif|jpg|jpeg|png)$/i.test(document.getElementById('picture').value);
  if (size_in_megabytes > 5) {
    accept = false;
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
  if (!extension){
    accept = false;
    alert('This document extension is not allowed.');
  }
  return accept;
});
</script>

<script>
function readURL(input) {

  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#prev').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}

$("#picture").change(function(){
    readURL(this);
});
</script>

app/views/advertisements/_search_form.html.erb
<%= form_tag(advertisements_path, method: :get) do %>
    <div class="input-group">
      <%= text_field_tag :term, "" , class: "form-control pull-right", placeholder:"Search by title", id: 'busqueda' %>
      <span class="input-group-btn"><%= submit_tag 'Search', name: nil, class: "btn btn-default", id: 'busqueda2' %></span>
    </div>
<% end %>
 

app/views/advertisements/_user_search_form.html.erb
<%= form_tag(static_pages_manageadvertisements_path, method: :get) do %>
    <div class="input-group">
      <%= text_field_tag :term, "" , class: "form-control pull-right", placeholder:"Search by title", id: 'busqueda' %>
      <span class="input-group-btn"><%= submit_tag 'Search', name: nil, class: "btn btn-default", id: 'busqueda2' %></span>
    </div>
<% end %>
 

app/views/advertisements/edit.html.erb
    <% provide(:title, "| Update Advertisement Info") %>
        <div class="page-header">
          <h1>Edit <small>Your advertisement</small></h1>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><h4>Edit your advertisement info</h4></div>
            <div class="panel-body">
                <%= render 'edit_form', advertisement: @advertisement %>
            </div>
            <div class="panel-footer">
                <%= link_to 'Show', @advertisement,  class: "btn btn-info" %> 
                <%= link_to 'Back', :back, class: "btn btn-default" %>
            </div>
        </div>

app/views/advertisements/index.html.erb
  <% provide(:title, "| Manage Advertisements") %>
  
  <div class="page-header">
    <h1>Advertisements <small>See all the advertisements</small></h1>
  </div>
  
  <%= render 'shared/show_flash' %>
  
  <div class="panel panel-default">
    <div class="panel-heading"><h4>Management</h4></div>
    <div class="panel-body scroll-x">
    
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr class='col-md-9'><%= render 'search_form' %></tr>
          <% @advertisements.each do |advert| %>
          <tr>
            <td class='col-md-9 wrap-word max-length'><h5><%= advert.title %></h5></td>
            <td><%= link_to 'Show', advert, class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_advertisement_path(advert), class: "btn btn-primary" %></td>
            <td><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      
      <div class="text-center">
        <%= will_paginate(@advertisements) %>
      </div>
      
    </div>
    <div class="panel-footer">
      <%= link_to 'New Advertisement', new_advertisement_path, class: "btn btn-success" %>
      <%= link_to 'Back', :back, class: "btn btn-default" %>
    </div>
  </div>

app/views/advertisements/new.html.erb
<% provide(:title, "| Create an Advertisement") %>
<div class="page-header center">
  <h1>New Advertisement <small>Create your advertisement here</small></h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <%= render 'form', advertisement: @advertisement %>
  </div>
</div>

<div class="boton_inicio center">
    <%= link_to 'Back', :back, class: "btn btn-default" %>
</div>

app/views/advertisements/show.html.erb
    <% provide(:title, "| Advertisements Info") %>
    
    <div class="page-header">
      <h1>Show <small>Your Advertisements Information</small></h1>
    </div>
    
    <%= render 'shared/show_flash' %>
    
    <div class="panel panel-default">
        <div class="panel-heading"><h4>See your Advertisements information</h4></div>
        <div class="panel-body">
            <h5><strong>Owner: </strong><%= user(advert(params[:id]).user_id).email %></h5>
            <h5><strong>Advertisement title: </strong><%= advert(params[:id]).title %></h5>
            <h5><strong>Advertisement create date: </strong><%= advert(params[:id]).created_at %></h5>
            <h5><strong>Advertisement last updated date: </strong><%= advert(params[:id]).updated_at %></h5>
            <h5><strong>Advertisement picture: </strong> <%= image_tag(advert(params[:id]).picture.url, class: 'img-responsive', alt: "imagen") %></h5>
        </div>
        <div class="panel-footer">
            <table>
            <tbody>
                <tr>
                  <td><%= link_to 'Back', :back, class: "btn btn-default" %></td>
                </tr>
            </tbody>
          </table>
        </div>
    </div>