config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :shorts, only: [:index, :show, :destroy]
    resources :user, only: [:index, :destroy, :show, :edit, :update]
    resources :admin_advertisements, only: [:index, :show, :destroy]
  end

  devise_for :users
  
  authenticated :user do
    root 'static_pages#welcome'
  end
  
  root 'static_pages#home'
  resources :shorts, only: [:show, :create, :new]
  resources :advertisements
  get 'greetings/hello'
  get ":id", to: "static_pages#redirect"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 80 }
  validates :picture, presence: true
  validate  :picture_size, on: :create
  mount_uploader :picture, PictureUploader
  
  def self.search(term)
    if term
      where('title LIKE ?', "%#{term}%").order('id DESC')
    else
      order('id DESC') 
    end
  end
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB.")
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short.rb
class Short < ApplicationRecord
    VALID_URL_REGEX = /\A((http|https|ftp|ftps):\/\/)?(([a-z0-9]+\:)?[a-z0-9]+\@)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z/
    before_validation :add_url_protocol
    validates :url, presence: true, format: { with: VALID_URL_REGEX }
    
    def short_url
        self.id.to_s(36)
    end
    
    def self.search(term)
        if term
          where('url LIKE ?', "%#{term}%").order('id ASC')
        else
          order('id ASC') 
        end
    end
    
    private
    
        def add_url_protocol
            unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
                self.url = "http://#{self.url}"
            end
        end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :advertisements, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def self.search(term)
    if term
      where('email LIKE ?', "%#{term}%").order('id DESC')
    else
      order('id DESC') 
    end
  end

end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
    before_action :correct_user, only: [:show, :destroy, :edit, :update]

    
    def index
        @advertisements = current_user.advertisements.search(params[:term]).paginate(page: params[:page])
    end
    
    def show
    end
    
    def new
        @advertisement = Advertisement.new
    end
    
    def edit
        @advertisement = Advertisement.find(params[:id])
    end
    
    def create
        @advertisement = current_user.advertisements.build(advertisement_params)
        respond_to do |format|
          if @advertisement.save
            format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully created.' }
            format.json { render :new, status: :created, location: @advertisement }
          else
            format.html { render :new }
            format.json { render json: @advertisement.errors, status: :unprocessable_entity }
          end
        end
    end

    def update
        @advertisement = Advertisement.find(params[:id])
        respond_to do |format|
          if @advertisement.update(advertisement_params)
            format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully updated.' }
            format.json { render :show, status: :ok, location: @short }
          else
            format.html { render :edit }
            format.json { render json: @advertisement.errors, status: :unprocessable_entity }
          end
        end
    end
    
    def destroy
        @advertisement = Advertisement.find(params[:id])
        @advertisement.destroy
        respond_to do |format|
            format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    
    private
        
        def advertisement_params
           params.require(:advertisement).permit(:title, :picture, :term)
        end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :is_female, :company) }
  end
  
  private
  
  def correct_user
    @user = User.find(Advertisement.find(params[:id]).user_id)
    unless current_user == @user || current_user.admin?
      respond_to do |format|
        format.html { redirect_to root_path, alert: 'Need to be administrator for this.' }
      end
    end  
  end
  
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
        render html: "Hello, World!"
  end
end

app/controllers/shorts_controller.rb
class ShortsController < ApplicationController
  before_action :set_short, only: [:show]

  # GET /shorts/1
  # GET /shorts/1.json
  def show
  end

  # GET /shorts/new
  def new
    @short = Short.new
  end


  # POST /shorts
  # POST /shorts.json
  def create
    @short = Short.new(short_params)
    respond_to do |format|
      if @short.save
        format.html { redirect_to root_path, notice: 'Short was successfully created.' }
        format.json { render :new, status: :created, location: @short }
      else
        format.html { render :new }
        format.json { render json: @short.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_short
      @short = Short.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_params
      params.require(:short).permit(:url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @short = Short.new
    @short2 = Short.last
  end
  
  def redirect
    if Advertisement.count > 0
      @advertisement = Advertisement.order("RANDOM()").first
      @advertiser = User.find(@advertisement.user_id).company
    end
    @redirection = Short.find(params[:id].to_i(36)).url
  end
  
  def welcome
    if current_user.is_female == true
      @gender = "Ms."
    else
      @gender = "Mr."
    end
    @name = current_user.name
    
    if current_user.admin?
      @role = "administrator"
    else
      @role = "advertiser"
    end
  end
  
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/shorts_helper.rb
module Admin::ShortsHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
    
    def advert(id)
        Advertisement.find(id)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/shorts_helper.rb
module ShortsHelper
    
    def link_url(url)
        link_to url, url, :target => "_blank" 
    end
    
    def short(id)
        Short.find(id)
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_helper.rb
module TestHelper
  module Features
    def login_user(email, password)
      visit '/users/sign_in'

      fill_in 'Email',    with: email
      fill_in 'Password', with: password

      click_button 'Log in'
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
    
    def user(id)
        User.find(id)
    end
    
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-default">
  <nav>
  <div class="container-fluid">
          <div class="navbar-header">
          <a class="navbar-brand">URL Shortener on Ruby on Rails 5</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="https://github.com/GuillermoCubero/short-url/blob/master/README.md" target="_blank">About project</a></li>
              <li><a href="https://github.com/GuillermoCubero/short-url" target="_blank">See the code</a></li>
            </ul>
          </div>
        </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
    <!— Brand and toggle get grouped for better mobile display —>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "URL Shortener", root_path, id: "logo" %>
    </div>

    <!— Collect the nav links, forms, and other content for toggling —>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li id='usuario'><h5>User: <%= current_user.email%></h5></li>
          <% if current_user.admin? %>
            <li><%= link_to "URLs", admin_shorts_path %></li>
            <li><%= link_to "Users", admin_user_index_path %></li>
            <li><%= link_to "Ads",  admin_admin_advertisements_path %></li>
          <% else %>
            <li><%= link_to "Ads", advertisements_path %></li>
          <% end %>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!— /.navbar-collapse —>
  </div><!— /.container-fluid —>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URL Shortener <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container full-screen">
      <section>
        <%= yield %>
      </section>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_devise_error_messages.html.erb
<% if !flash.empty? %>
  <%= devise_error_messages! %>
  <div class="row">
      <div class="col-md-10 col-md-offset-1 center">
        <div class="alert alert-success" role="alert">
          <% flash.each do |key, value| %>
             <div id="notice <%= key %>"><%= value %></div>
          <% end %>
        </div>
      </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            <h4>The form contains <%= pluralize(object.errors.count, "error") %>.</h4>
        </div>
        <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><h5><%= message %></h5></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_show.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h4>See your URL information</h4></div>
    <div class="panel-body">
        <h5><strong>Url: </strong><%= link_url(@short2.url) %></h5>
        <h5><strong>Shorted Url: </strong><%= link_to request.base_url+'/'+@short2.short_url, @short2.url, id: 'id-of-link', :target => "_blank" %></h5>
    </div>
    <div class="panel-footer">
    <%= link_to 'Edit', edit_short_path(@short2), class: "btn btn-primary" %> 
</div>

app/views/shared/_show_flash.html.erb
<% if !flash.empty? %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1 center">
      <% if flash.notice() %>
      <div class="alert alert-success" role="alert">
        <p id="notice"><%= flash[:notice] %></p>
      </div>
      <% elsif flash.alert() %>
      <div class="alert alert-danger" role="alert">
        <p id="notice"><%= flash[:alert] %> </p>
      </div>
      <% end %>
    </div>
  </div>
<% end %>